### ISSUE TITLE
Lambda JS file is issing

### ISSUE THREAD

**Issue by WhyNotHugo** [naftulikay/terraform-aws-private-ecr-domain#1]
There's a reference to it when generating the archive: ` "${path.module}/lambda"`.
But it seems that you forgot to commit it?

**Comment by naftulikay** [comment]
@WhyNotHugo thank you for filing, I have added the Lambda function source code in [`3943e43`][commit] and it is now available in `master`. The function is well-documented, let me know if anything is unclear, closing as fixed.

 [commit]: https://github.com/naftulikay/terraform-aws-private-ecr-domain/commit/7da8913bd7c2228e9816e4e05d879b27c3943e43

**Comment by WhyNotHugo** [comment]
Thanks!
